import type { ClientSummary, Run } from '../types/api.ts';

/** Entirely synthetic examples, unrelated to the private Parquet dataset. */
export const demoRun: Run = {
  run_id: 'demo-july-2026',
  created_at: '2026-09-23T09:00:00Z',
  status: 'completed',
  stage: null,
  summary: {
    period_start: '2026-07-01',
    period_end: '2026-07-31',
    n_nodes: 7,
    n_edges: 7,
    n_transactions: 10,
    n_seed: 2,
    n_clusters: 2,
    n_isolated: 1,
    n_truncated: 1,
    sum_kzt: 830000,
    elapsed_seconds: 0.84,
  },
  warnings: [
    'Роли и приоритеты в этом примере заданы вручную для проверки интерфейса. Исходный датасет не анализировался.',
  ],
  error: null,
};

export const demoClients: ClientSummary[] = [
  {
    gid: '900000000000000105',
    rank: 1,
    role: 'consolidator',
    role_score: 0.72,
    priority_score: 0.82,
    cluster_id: 0,
    depth: 2,
    is_seed: false,
    truncated_by_depth: false,
    in_deg: 3,
    out_deg: 1,
    in_kzt: 280000,
    out_kzt: 250000,
    evidence:
      'Получает 280 000 KZT от 3 клиентов. Признаки сбора средств; полный баланс неизвестен.',
    priority_reason_short:
      '3 отправителя; объединяет несколько направлений переводов.',
  },
  {
    gid: '900000000000000101',
    rank: 2,
    role: 'peripheral',
    role_score: 0,
    priority_score: 0.71,
    cluster_id: 0,
    depth: 0,
    is_seed: true,
    truncated_by_depth: false,
    in_deg: 0,
    out_deg: 3,
    in_kzt: 0,
    out_kzt: 300000,
    evidence:
      'Отправляет 300 000 KZT трём клиентам. Входящие исходного клиента могут быть неполными.',
    priority_reason_short:
      '300 000 KZT наблюдаемой активности; 3 исходящие связи.',
  },
  {
    gid: '900000000000000102',
    rank: 3,
    role: 'transit',
    role_score: 0.35,
    priority_score: 0.63,
    cluster_id: 0,
    depth: 1,
    is_seed: false,
    truncated_by_depth: false,
    in_deg: 1,
    out_deg: 1,
    in_kzt: 120000,
    out_kzt: 100000,
    evidence:
      'Вход 120 000 KZT, выход 100 000 KZT. Суммы сопоставимы; хронология не проверена.',
    priority_reason_short:
      'Связывает отправителя и сборщика; активность 220 000 KZT.',
  },
  {
    gid: '900000000000000103',
    rank: 4,
    role: 'transit',
    role_score: 0.62,
    priority_score: 0.58,
    cluster_id: 0,
    depth: 1,
    is_seed: false,
    truncated_by_depth: false,
    in_deg: 1,
    out_deg: 1,
    in_kzt: 80000,
    out_kzt: 80000,
    evidence:
      'Вход и выход по 80 000 KZT. Кандидат на транзит по месячным суммам.',
    priority_reason_short:
      'Две направленные связи; структурно достижим из исходного клиента.',
  },
  {
    gid: '900000000000000104',
    rank: 5,
    role: 'transit',
    role_score: 0.65,
    priority_score: 0.54,
    cluster_id: 0,
    depth: 1,
    is_seed: false,
    truncated_by_depth: false,
    in_deg: 1,
    out_deg: 1,
    in_kzt: 100000,
    out_kzt: 100000,
    evidence:
      'Вход и выход по 100 000 KZT. Кандидат на транзит; движение тех же денег не доказано.',
    priority_reason_short: '200 000 KZT наблюдаемой активности и 2 связи.',
  },
  {
    gid: '900000000000000106',
    rank: 6,
    role: 'peripheral',
    role_score: 0,
    priority_score: 0.31,
    cluster_id: 0,
    depth: 4,
    is_seed: false,
    truncated_by_depth: true,
    in_deg: 1,
    out_deg: 0,
    in_kzt: 250000,
    out_kzt: 0,
    evidence:
      'Вход 250 000 KZT; узел на границе 4-го колена. Дальнейшие переводы не наблюдаются.',
    priority_reason_short:
      'Получено 250 000 KZT; продолжение потока неизвестно.',
  },
  {
    gid: '900000000000000107',
    rank: 7,
    role: 'peripheral',
    role_score: 0,
    priority_score: 0,
    cluster_id: 1,
    depth: 0,
    is_seed: true,
    truncated_by_depth: false,
    in_deg: 0,
    out_deg: 0,
    in_kzt: 0,
    out_kzt: 0,
    evidence:
      'Входящих связей 0, исходящих 0. Роль по имеющейся выгрузке не определена.',
    priority_reason_short:
      'Связей нет; транзакционных оснований для приоритета недостаточно.',
  },
];
